version: '3.8'

services:
  # Enterprise MCP Server - Simple & Clean
  enterprise-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # MCP Server
    environment:
      - ENVIRONMENT=production
      - ENABLE_TELEMETRY=false  # Set to true for OpenTelemetry
      - LOG_LEVEL=INFO
      - REDIS_URL=redis://redis:6379/0
      - MCP_TRANSPORT=sse  # Use SSE for remote access
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8000
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache (for agent caching)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
