# Enterprise MCP Server Configuration
# Following ADK MCP documentation patterns

server:
  name: "enterprise-tools-mcp-server"
  version: "1.0.0"
  description: "Enterprise tools exposed via MCP protocol"
  
# MCP Protocol Configuration
mcp:
  protocol_version: "2024-11-05"
  capabilities:
    tools: true
    resources: false
    prompts: false
  
# Tool Configuration
tools:
  query_database:
    name: "query_database"
    description: "Execute SQL queries against enterprise databases"
    input_schema:
      type: "object"
      properties:
        query:
          type: "string"
          description: "SQL query to execute"
        database:
          type: "string"
          description: "Target database name"
          default: "default"
        auth_token:
          type: "string"
          description: "Authentication token"
      required: ["query"]
  
  search_documents:
    name: "search_documents"
    description: "Search through enterprise document repositories"
    input_schema:
      type: "object"
      properties:
        query:
          type: "string"
          description: "Search query"
        repository:
          type: "string"
          description: "Document repository"
          default: "default"
        limit:
          type: "integer"
          description: "Maximum number of results"
          default: 10
        auth_token:
          type: "string"
          description: "Authentication token"
      required: ["query"]
  
  run_analytics:
    name: "run_analytics"
    description: "Execute analytics queries and generate business insights"
    input_schema:
      type: "object"
      properties:
        analysis_type:
          type: "string"
          description: "Type of analysis to perform"
        parameters:
          type: "object"
          description: "Analysis parameters"
        auth_token:
          type: "string"
          description: "Authentication token"
      required: ["analysis_type", "parameters"]

# Security Configuration
security:
  authentication_required: true
  token_validation: true
  
# Observability Configuration
observability:
  tracing_enabled: true
  metrics_enabled: true
  logging_level: "INFO"
