name: "ReportingAgent"
description: "Specialized agent for business reporting and analytics"

llm:
  provider: "litellm"
  model: "azure/gpt-4o"
  temperature: 0.1
  max_tokens: 2000
  api_key: "${AZURE_API_KEY}"
  api_base: "${AZURE_API_BASE}"
  api_version: "${AZURE_API_VERSION}"

mcp_server:
  url: "https://mcp-server-service-url"
  tools: ["run_analytics", "query_database", "search_documents"]
  timeout: 30

capabilities:
  - "Report generation"
  - "Analytics processing"
  - "Business insights"
  - "Data visualization"

observability:
  tracing: true
  metrics: true
  log_level: "INFO"
