name: "EnterpriseOrchestrator"
description: "Central orchestrator for enterprise multi-agent system"

llm:
  provider: "litellm"
  model: "azure/gpt-4o"
  temperature: 0.1
  max_tokens: 2000
  api_key: "${AZURE_API_KEY}"
  api_base: "${AZURE_API_BASE}"
  api_version: "${AZURE_API_VERSION}"

agents:
  - name: "DataSearchAgent"
    url: "https://data-search-agent-service-url"
    capabilities: ["database queries", "document search", "data retrieval"]
  
  - name: "ReportingAgent"
    url: "https://reporting-agent-service-url"
    capabilities: ["report generation", "analytics", "business insights"]

observability:
  tracing: true
  metrics: true
  log_level: "INFO"
