name: "DataSearchAgent"
description: "Specialized agent for enterprise data search and retrieval"

llm:
  provider: "litellm"
  model: "azure/gpt-4o"
  temperature: 0.1
  max_tokens: 1500
  api_key: "${AZURE_API_KEY}"
  api_base: "${AZURE_API_BASE}"
  api_version: "${AZURE_API_VERSION}"

mcp_server:
  url: "https://mcp-server-service-url"
  tools: ["query_database", "search_documents"]
  timeout: 30

capabilities:
  - "SQL query execution"
  - "Document search"
  - "Data extraction"
  - "Result formatting"

observability:
  tracing: true
  metrics: true
  log_level: "INFO"
